---
kind: pipeline
name: default-linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.5.5
  commands:
  - dapper ci
  privileged: true
  volumes:
  - name: socket
    path: /var/run/docker.sock
  when:
    event:
    - push
    - pull_request
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/configmap-reload
    tag: ${DRONE_TAG}-linux-amd64
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/heads/rancher
    - refs/tags/*
    event:
    - tag

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
name: default-windows-20H2

platform:
  os: windows
  arch: amd64
  version: 20H2

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-20H2-amd64
  - name: build
    pull: always
    image: rancher/dapper:v0.5.5
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.5
    commands:
      - "cp -r ./bin/* ./package/windows/"
    when:
      event:
        - push
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - SERVERCORE_VERSION=20H2
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/configmap-reload
      tag: ${DRONE_TAG}-windows-20H2
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/rancher
        - refs/tags/*

  - name: slack_notify
    image: plugins/slack
    settings:
      template: "Build {{build.link}} failed to publish an image/artifact.\n"
      username: Drone_Publish
      webhook:
        from_secret: slack_webhook
    when:
      event:
        exclude:
          - pull_request
      instance:
        - drone-publish.rancher.io
      status:
        - failure

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote


---
kind: pipeline
name: default-windows-2004

platform:
  os: windows
  arch: amd64
  version: 2004

# remove this and use upstream images when https://github.com/drone/drone-git/pull/25 is merged
clone:
  disable: true

steps:
  - name: clone
    image: luthermonson/drone-git:windows-2004-amd64
  - name: build
    pull: always
    image: rancher/dapper:v0.5.5
    commands:
      - dapper.exe -f Dockerfile-windows.dapper -d ci
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - push
        - pull_request
        - tag

  - name: stage-binaries
    image: rancher/dapper:v0.5.5
    commands:
      - "cp -r ./bin/* ./package/windows/"
    when:
      event:
        - push
        - tag

  - name: docker-publish
    image: plugins/docker
    settings:
      build_args:
        - SERVERCORE_VERSION=2004
        - ARCH=amd64
        - VERSION=${DRONE_TAG}
      context: package/windows
      custom_dns: 1.1.1.1
      dockerfile: package/windows/Dockerfile
      password:
        from_secret: docker_password
      repo: rancher/configmap-reload
      tag: ${DRONE_TAG}-windows-2004
      username:
        from_secret: docker_username
    volumes:
      - name: docker_pipe
        path: \\\\.\\pipe\\docker_engine
    when:
      event:
        - tag
      ref:
        - refs/heads/rancher
        - refs/tags/*

  - name: slack_notify
    image: plugins/slack
    settings:
      template: "Build {{build.link}} failed to publish an image/artifact.\n"
      username: Drone_Publish
      webhook:
        from_secret: slack_webhook
    when:
      event:
        exclude:
          - pull_request
      instance:
        - drone-publish.rancher.io
      status:
        - failure

volumes:
  - name: docker_pipe
    host:
      path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
      - promote

---
kind: pipeline
name: default-windows-1909

platform:
  os: windows
  arch: amd64
  version: 1909

steps:
- name: build
  pull: always
  image: rancher/dapper:v0.5.5
  commands:
  - dapper.exe -f Dockerfile-windows.dapper -d ci
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    - pull_request
    - tag

- name: stage-binaries
  image: rancher/dapper:v0.5.5
  commands:
    - "cp -r ./bin/* ./package/windows/"
  when:
    event:
      - push
      - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - SERVERCORE_VERSION=1909
    - ARCH=amd64
    - VERSION=${DRONE_TAG}
    context: package/windows
    custom_dns: 1.1.1.1
    dockerfile: package/windows/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/configmap-reload
    tag: ${DRONE_TAG}-windows-1909
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - tag
    ref:
    - refs/heads/rancher
    - refs/tags/*

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed to publish an image/artifact.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
    status:
    - failure

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
name: default-windows-1903

platform:
  os: windows
  arch: amd64
  version: 1903

steps:
- name: build
  pull: always
  image: rancher/dapper:v0.5.5
  commands:
  - dapper.exe -f Dockerfile-windows.dapper -d ci
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    - pull_request
    - tag

- name: stage-binaries
  image: rancher/dapper:v0.5.5
  commands:
    - "cp -r ./bin/* ./package/windows/"
  when:
    event:
      - push
      - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - SERVERCORE_VERSION=1903
    - ARCH=amd64
    - VERSION=${DRONE_TAG}
    context: package/windows
    custom_dns: 1.1.1.1
    dockerfile: package/windows/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/configmap-reload
    tag: ${DRONE_TAG}-windows-1903
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - tag
    ref:
    - refs/heads/rancher
    - refs/tags/*

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed to publish an image/artifact.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
    status:
    - failure

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
name: default-windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: build
  pull: always
  image: rancher/dapper:v0.5.5
  commands:
  - dapper.exe -f Dockerfile-windows.dapper -d ci
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - push
    - pull_request
    - tag

- name: stage-binaries
  image: rancher/dapper:v0.5.5
  commands:
    - "cp -r ./bin/* ./package/windows/"
  when:
    event:
      - push
      - tag

- name: docker-publish
  image: plugins/docker
  settings:
    build_args:
    - SERVERCORE_VERSION=1809
    - ARCH=amd64
    - VERSION=${DRONE_TAG}
    context: package/windows
    custom_dns: 1.1.1.1
    dockerfile: package/windows/Dockerfile
    password:
      from_secret: docker_password
    repo: rancher/configmap-reload
    tag: ${DRONE_TAG}-windows-1809
    username:
      from_secret: docker_username
  volumes:
  - name: docker_pipe
    path: \\\\.\\pipe\\docker_engine
  when:
    event:
    - tag
    ref:
    - refs/heads/rancher
    - refs/tags/*

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed to publish an image/artifact.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
    status:
    - failure

volumes:
- name: docker_pipe
  host:
    path: \\\\.\\pipe\\docker_engine

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: amd64

steps:
- name: push-manifest
  image: plugins/manifest
  settings:
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    username:
      from_secret: docker_username
  when:
    event:
    - tag

- name: slack_notify
  image: plugins/slack
  settings:
    template: "Build {{build.link}} failed to push manifests.\n"
    username: Drone_Publish
    webhook:
      from_secret: slack_webhook
  when:
    event:
      exclude:
      - pull_request
    instance:
    - drone-publish.rancher.io
    status:
    - failure

trigger:
  event:
    exclude:
    - promote

depends_on:
- default-linux-amd64
- default-windows-1809
- default-windows-1903
- default-windows-1909
- default-windows-2004
- default-windows-20H2

...
